sudo: required
language: python

services:
  - docker

install:
  - pip install coverage codecov

before_script:
  - ./ci/start.sh

after_script:
  - ./ci/stop.sh

script:
  - ./ci/run-tests.sh

after_success:
  - TRAVIS_PYTHON_VERSION=3.6 codecov
